### ISSUE TITLE
Lab 5.2 - Expectations on login

### ISSUE THREAD

**Issue by Jidrys** [adaltas/ece-webtech-2022-spring#11]
---
name: Lab 5.2 - Expectations on login
about: What should be the organization of the login part
title: 'Lab 5.2 - Expectations on login'
labels: 'Lab5, login'
assignees: 'Sergei Kudinov'

---

## Description

In the Lab5 we have to do a login screen in out chat application. 
My question is: should the login screen be in a separate page, or should it be "on top" of our application and disapear as we successfully login ? 

## Screenshot

![image](https://user-images.githubusercontent.com/57490679/155303464-408e18d1-2997-4d86-9f09-b1714b54bbb4.png)

**Comment by sergkudinov** [comment]
@Jidrys 
I pushed the lab 5 initial updates, find it in your corrections repository under the tag `front-end@v0.3.0-lab5`.
Sorry for being late with this, hope you have managed this by your own.
